import{a as m,i as n,S as g}from"./assets/vendor-64b55ca9.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&s(c)}).observe(document,{childList:!0,subtree:!0});function r(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=r(e);fetch(e.href,o)}})();function h(a,t=!0){const r=document.querySelector(".gallery"),s=a.map(e=>`
      <div class="photo-card">
        <a href="${e.largeImageURL}" target="_blank">
          <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
        </a>
        <div class="info">
          <p><i class="img-text">Likes </i><span>${e.likes}</span></p>
          <p><i class="img-text">Views </i><span>${e.views}</span></p>
          <p><i class="img-text">Comments </i><span>${e.comments}</span></p>
          <p><i class="img-text">Downloads </i><span>${e.downloads}</span></p>
        </div>
      </div>
    `).join("");t?r.insertAdjacentHTML("beforeend",s):r.innerHTML=s,f.refresh()}const b="42334631-07f239856d3b6a49db441bfb9";let d=0,u=0;function S(a,t){let r;return function(...s){const e=this;clearTimeout(r),r=setTimeout(()=>a.apply(e,s),t)}}function q(){const t=document.querySelector(".photo-card").getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})}const v=S(q,100);async function y(a,t){const r=document.querySelector(".loader"),s=document.querySelector("#load-more");s.style.display="none",r.style.display="block";try{const e=await m.get(`https://pixabay.com/api/?key=${b}&q=${encodeURIComponent(a)}&image_type=photo&orientation=horizontal&safesearch=true&per_page=15&page=${t}`);d=e.data.totalHits,u+=e.data.hits.length,console.log(e.data),r.style.display="none",e.data.hits.length===0?d===0?n.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!"}):u>=d&&n.info({title:"Info",message:"We are sorry, but you have reached the end of search results."}):(h(e.data.hits),f.refresh(),v(),s.style.display="block")}catch(e){console.error("Error fetching images:",e),r.style.display="none",n.error({title:"Error",message:"Failed to fetch images. Please try again later."})}}const f=new g(".gallery a"),L=document.querySelector("#search-form"),p=document.querySelector("#search-input");let l="",i=1;L.addEventListener("submit",a=>{const t=document.querySelector(".gallery");t.innerHTML="",l=p.value.trim(),i=1,a.preventDefault();const r=document.querySelector(".loader");if(r.style.display="block",!l){n.warning({title:"Warning",message:"Please enter a search query"});return}setTimeout(()=>{y(l,i),p.value=""},200)});document.querySelector("#load-more").addEventListener("click",()=>{i+=1,y(l,i)});
//# sourceMappingURL=commonHelpers.js.map
